//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Management.Infrastructure.Properties.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ChangePasswordFailed.
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ChangePasswordSuccess.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrEmailAlreadyExist.
        /// </summary>
        public static string ErrEmailAlreadyExist {
            get {
                return ResourceManager.GetString("ErrEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrEmailDuplicate.
        /// </summary>
        public static string ErrEmailDuplicate {
            get {
                return ResourceManager.GetString("ErrEmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrEmailNull.
        /// </summary>
        public static string ErrEmailNull {
            get {
                return ResourceManager.GetString("ErrEmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_GetTokenFailed.
        /// </summary>
        public static string ErrGetTokenFailed {
            get {
                return ResourceManager.GetString("ErrGetTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrIsDeletedFalse.
        /// </summary>
        public static string ErrIsDeletedFalse {
            get {
                return ResourceManager.GetString("ErrIsDeletedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_LoginFailed.
        /// </summary>
        public static string ErrLoginFailed {
            get {
                return ResourceManager.GetString("ErrLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrPasswordNull.
        /// </summary>
        public static string ErrPasswordNull {
            get {
                return ResourceManager.GetString("ErrPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrStatusInvalid.
        /// </summary>
        public static string ErrStatusInvalid {
            get {
                return ResourceManager.GetString("ErrStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrStatusNull.
        /// </summary>
        public static string ErrStatusNull {
            get {
                return ResourceManager.GetString("ErrStatusNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserCodeAlreadyExist.
        /// </summary>
        public static string ErrUserCodeAlreadyExist {
            get {
                return ResourceManager.GetString("ErrUserCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserCodeDuplicate.
        /// </summary>
        public static string ErrUserCodeDuplicate {
            get {
                return ResourceManager.GetString("ErrUserCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserCodelNull.
        /// </summary>
        public static string ErrUserCodelNull {
            get {
                return ResourceManager.GetString("ErrUserCodelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserIsDeleted.
        /// </summary>
        public static string ErrUserIsDeleted {
            get {
                return ResourceManager.GetString("ErrUserIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserIsLogin.
        /// </summary>
        public static string ErrUserIsLogin {
            get {
                return ResourceManager.GetString("ErrUserIsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserNameAlreadyExist.
        /// </summary>
        public static string ErrUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("ErrUserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserNameDuplicate.
        /// </summary>
        public static string ErrUserNameDuplicate {
            get {
                return ResourceManager.GetString("ErrUserNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserNamelNull.
        /// </summary>
        public static string ErrUserNamelNull {
            get {
                return ResourceManager.GetString("ErrUserNamelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserNotExist.
        /// </summary>
        public static string ErrUserNotExist {
            get {
                return ResourceManager.GetString("ErrUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserTypeInvalid.
        /// </summary>
        public static string ErrUserTypeInvalid {
            get {
                return ResourceManager.GetString("ErrUserTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityService_ErrUserTypeNull.
        /// </summary>
        public static string ErrUserTypeNull {
            get {
                return ResourceManager.GetString("ErrUserTypeNull", resourceCulture);
            }
        }
    }
}
